### ISSUE TITLE
Provide documentation for external users who want to upload reports

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/reports#362]
Currently the [existing documentation](https://bennettinstitute-team-manual.pages.dev/products/opensafely-reports/) is in the team manual and aimed at people working within the Bennett Institute.

A new section should be added to the docs.opensafely.org site to allow the pilot users of reports.opensafely.org to tell them how to:

1. Request access (note: pilot users only for the moment)
2. Upload draft a report from the jobs site
3. Take the correct steps to ensure the report can be published (i.e the publication process)
4. Turn a draft report into a published report

Note: customisation of the report styling should be addressed in a separate ticket
Note: as we're piloting this to a small number of users, it may make more sense to move the instructions into a Google doc first and then update the main docs site later on

### Acceptance criteria
* The instructions are accessible to the pilot users
* The instructions cover the four points above
* At least one co-pilot has reviewed the instructions

**Comment by lucyb** [comment]
Request from Brian: review the current wording when moving the docs across to docs.opensafely.org. For example, we should remove the use of the word "external" when referring to users or reports. 

We should also make clear on the docs that this is a pilot and open to a limited number of users at the moment.

**Comment by LFISHER7** [comment]
I'm going to be "co-piloting" the pilot users for this so happy to help with rewording the docs or reviewing the instructions once they are ready.

**Comment by ghickman** [comment]
@lucyb – What is the publication process for a report? and is that related to publishing outputs on job-server?

**Comment by lucyb** [comment]
@ghickman I don't know I'm afraid. I know that the researchers have a process for making a report available on reports.opensafely.org. Can you ask @rose-higgins maybe?

**Comment by lucyb** [comment]
@LFISHER7 During the pilot, uploads will only be done through job server. Is the plan to walk the two pilot users through the process or do we need to come up with some supporting documentation for that as well?

Is it worth you and @ghickman going through the existing documentation and seeing what should be made available and what's missing?

**Comment by LFISHER7** [comment]
I will likely walk the pilot users through but it's probably a good opportunity to road test some initial documentation too? I'm happy to run through the existing docs

**Comment by ghickman** [comment]
I'm slicing and dicing the existing stuff to make it match the admin interface so any user can follow it through from clicking the "Add" button to getting a published report.  I'll definitely get a review from @LFISHER7 when I've got something meaningful!

@LFISHER7 – Can I just check a process point though, is the very high level flow:
1. create draft report
2. user pings Bennett, essentially following the relevant parts of our internal publication flow
3. report is made public

**Comment by ghickman** [comment]
Done in opensafely/documentation#994
