### ISSUE TITLE
Provide tech support with documentation for managing external users

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/reports#364]
As part of a pilot, we're allowing a small number of external users access to add reports to reports.opensafely.org

We're updating the documentation to allow them to do this [here](https://github.com/opensafely-core/output-explorer/issues/362).

So, we should also ensure the documentation in the team manual is updated so that anyone on tech support knows how to manage these user accounts and support the users with any requests they may have

Acceptance criteria
* Tech support are aware of the pilot and where to find the playbooks and public documentation
* Tech support have some instructions for supporting users who are using reports.opensafely.org
* Tech support know how to create user accounts for new pilot users

**Comment by ghickman** [comment]
We've decided that @LFISHER7 will be handling the setup of the pilot users and we'll re-evaluate what's necessary to support pilot users once the pilot is over.
