### ISSUE TITLE
Admin fields for external reports

### ISSUE THREAD

**Issue by tomodwyer** [opensafely-core/reports#376]
We want users outside of Bennett Institute for Applied Data Science to be able to add reports to the website. To show that these come from external collaborators, we need to add the following fields to each report:

- **Mark as external** – checkbox to trigger the following required fields
- **Organisation** – `<select>` element containing all partner organisations
  - **Logo** - linked to an org
  - **Homepage link** - linked to an org
- **Partner description** – `<textarea>` element to add the initial description ("Lorem ipsum" text in the above video/screenshot)

Organisations will need to be added in the admin section and be able to be updated by Bennett Institute for Applied Data Science staff.

When a report is marked as external, it should send these admin fields to the template so that styles can be applied (#377).

**Comment by ghickman** [comment]
@tomodwyer – how is Partner description supposed to differ to the existing description field?

**Comment by tomodwyer** [comment]
@ghickman yes, it was to explain the relationship between the external org, and why this report is on the OpenSAFELY website (see image below)

![](https://user-images.githubusercontent.com/24863179/188125748-bfdceec3-bb97-4326-842d-941df8462d9e.png)
