### ISSUE TITLE
Run as a non-root user

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/reports#524]
Currently our Docker containers are running using root in production and dev. This used to be required for the Action Docker images and they share the same base image, so it stopped us from updating other services. However, these have since been updated and no longer require root privileges, which means it should be quite straightforward to update our remaining Docker images, most of which run internet-facing services.

This ticket is to change the user that's used to run Reports to a non-root user.

[Link to the risk in the Risk Register](https://docs.google.com/spreadsheets/d/14p4zoMhV5iAPTjzfTHaHDYBzkZ9Giw2yLUMTXCJdJFU/edit#gid=0&range=A30)

[Link to the change in Job Server to run as non-root](https://github.com/opensafely-core/job-server/commit/d76d26796a69b44a17b640be0870ce20be557fe8)

Part of https://github.com/opensafely-core/security/issues/17

**Comment by madwort** [comment]
more difficult as needs tests creating first

**Comment by madwort** [comment]
https://github.com/opensafely-core/reports/pull/564 & https://github.com/ebmdatalab/sysadmin/pull/305

**Comment by madwort** [comment]
done & deployed

**Comment by madwort** [comment]
This has caused some issues in production relating to cache files. It seems that the app writes cache data to files inside the docker image, not into the file storage provided by dokku. This means that there are file permission problems opening the cache files. I think we can work around one of these easily by telling the http_cache to use the dokku storage thusly:

```
dokku config:set reports REQUESTS_CACHE_NAME="/storage/http_cache"
```

but I think we also have a similar issue with some kind of github cache, and it's not clear to me yet what to do about that. 

https://github.com/opensafely-core/reports/pull/577

**Comment by madwort** [comment]
redone & deployed & now works correctly as far as I can see
