### ISSUE TITLE
Branch for ethnicity short data report has gone away

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/reports#561]
The branch, `notebook_simplify`, for [this report](https://reports.opensafely.org/admin/reports/report/22/change/) has gone away on GitHub.

Can we find the branch and restore it? Do we know why it went away?

**Comment by ghickman** [comment]
The branch was deleted after [PR#60](https://github.com/opensafely/ethnicity-short-data-report/pull/60) was merged.

It looks like the `local/` and `notebooks_jupyter/` paths was only ever committed to that branch so a local repo checkout has no reference to them.

GitHub still maintains references at least, likely because of the PRs, so we can get the latest versions from [c47f4e6](https://github.com/opensafely/ethnicity-short-data-report/tree/c47f4e67d3a0c36e2737b7e66139a0d6621f1f2d).

**Comment by andrewscolm** [comment]
reports site has now been updated with the job-server hosted html 😄
