### ISSUE TITLE
pancreatic-cancer's file has been redacted

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/reports#562]
The underlying ReleaseFile on job-server for [this report](https://reports.opensafely.org/admin/reports/report/28/change/) was redacted by Louis on 2023-01-17.

We don't currently pass redaction info out via the API, we raise a 404.  Neither do we inform job-server there is a report tied to a ReleaseFile.

**Comment by andrewscolm** [comment]
The draft report has now been deleted.
