### ISSUE TITLE
reports page shows 404 with incorrect url

### ISSUE THREAD

**Issue by madwort** [opensafely-core/reports#584]
this sentry error https://ebm-datalab.sentry.io/issues/4744291438/?project=5756541&query=strptime&referrer=issue-stream&statsPeriod=14d&stream_index=0
shows this 404 page (only when not logged in to the reports site) https://reports.opensafely.org/reports/clinical-coding-of-primary-care-covid-codes-in-england/
which is because this url https://jobs.opensafely.org/primary-care-covid-codes-research/primary-care-covid-codes-research/outputs/10/output/primary-care-covid-codes.html/ does not have a last-modified header. Removing the trailing slash https://jobs.opensafely.org/primary-care-covid-codes-research/primary-care-covid-codes-research/outputs/10/output/primary-care-covid-codes.html returns some content & a last-modified header, so I assume this is an incorrect url, possibly due to modification by @ghickman this week. 

Actions:
- [ ] check & fix url

Optional follow-ups:

- [ ] maybe add a 301 on job-server for urls such as this? (if that even makes sense, maybe it doesn't)
- [ ] maybe handle this error case better in reports?

**Comment by madwort** [comment]
We now think that Colm fixed the url himself after seeing the error & then @madwort was just chasing shadows when looking at the 404 as he was logged out - the report is draft so it should not be visible to logged-out users. Possibly no further action needed!

**Comment by lucyb** [comment]
I've confirmed with Colm that everything is working as expected now, so I'll close this ticket.
